### ISSUE TITLE
Left align when no thumbnail image. 

### ISSUE THREAD

**Issue by ianblair44** [BuildFire/pluginPluginMediaCenterRSS#5]
The entries should be over to the left right now. 

<img width="415" alt="screen shot 2015-09-11 at 9 58 56 am" src="https://cloud.githubusercontent.com/assets/2794086/9821017/64a4ec7c-586c-11e5-8c71-37d046a585b3.png">

**Comment by sandeepchhapola** [comment]
its working fine now, Please review it.
