### ISSUE TITLE
Gap Above List Items

### ISSUE THREAD

**Issue by ianblair44** [BuildFire/pluginPluginMediaCenterRSS#6]
There should not be a gap when there is no text in the WYSIWYG or no image carousel.
<img width="415" alt="screen shot 2015-09-11 at 9 58 56 am" src="https://cloud.githubusercontent.com/assets/2794086/9821047/97c320a6-586c-11e5-948a-14a49a505910.png">

**Comment by sandeepchhapola** [comment]
hey Ian, it is resoled. please review it.
