### ISSUE TITLE
Design Layouts Stretched

### ISSUE THREAD

**Issue by ianblair44** [BuildFire/pluginPluginMediaCenterRSS#7]
These are all stretched and not in their original aspect ratio 

<img width="749" alt="screen shot 2015-09-11 at 10 05 49 am" src="https://cloud.githubusercontent.com/assets/2794086/9821091/d6c1bd12-586c-11e5-8e7e-cf05e3f66fa9.png">

**Comment by sandeepchhapola** [comment]
its working fine now, Please review it.
