### ISSUE TITLE
Stripping HTML and CSS

### ISSUE THREAD

**Issue by ianblair44** [BuildFire/pluginPluginMediaCenterRSS#9]
It looks like right now we are stripping all HTML and CSS in the body.

Let's only strip the CSS from the body. I still want people to be able to have h1 tags and ul's etc...

We should make sure to strip all HTML though from the summary and title.

**Comment by lakshaydulani** [comment]
Hello Ian,

Ok, we will strip the HTML tags from Title and Summary and render them as plain text.
And, Body will be rendered as HTML without its style.

**Comment by ianblair44** [comment]
Perfect.

**Comment by sandeepchhapola** [comment]
its working fine now. please review it.
